### ISSUE TITLE
user-data file [...] could not be found

### ISSUE THREAD

**Issue by splattner** [cloudscale-ch/docker-machine-driver-cloudscale#4]
When using this docker-machine-driver together with https://github.com/cloudscale-ch/ui-driver-cloudscale and you wanna pass some userdata, e.g.

```
#cloud-config
coreos:
  units:
    - name: "docker.service"
      command: "start"
      enable: true
```

then you get an error:

`Error with pre-create check: "user-data file #cloud-config\ncoreos:\n units:\n - name: \"docker.service\"\n command: \"start\"\n enable: true could not be found"; Timeout waiting for ssh key`.

The driver wants a file: https://github.com/cloudscale-ch/docker-machine-driver-cloudscale/blob/master/driver.go#L164 & https://github.com/cloudscale-ch/docker-machine-driver-cloudscale/blob/master/driver.go#L175

it would be nice to also allow passing a string with the userdata instead of a file, as passing a file is not working in combination with the Rancher UI driver
